ManagingPersonalContacts/Controllers/PersonalContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ManagingPersonalContacts.Models;

namespace ManagingPersonalContacts.Controllers
{
    public class PersonalContactsController : Controller
    {
        private PersonalContactDBContext db = new PersonalContactDBContext();

        // GET: /PersonalContacts/
        public ActionResult Index()
        {
            return View(db.PersonalContacts.ToList());
        }

        // GET: /PersonalContacts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonalContact personalcontact = db.PersonalContacts.Find(id);
            if (personalcontact == null)
            {
                return HttpNotFound();
            }
            return View(personalcontact);
        }

        // GET: /PersonalContacts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /PersonalContacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonalContactID,FirstName,SurName,DateOfBirth,Address,PhoneNumber,IBAN,ImgFileName,ImgContentType,ImgContent,ImgFileNameGen")] PersonalContact personalcontact, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                //NEw
                Address address = new Address();
                PhoneNumber phoneNumber = new PhoneNumber();
                Bank bank = new Bank();
                if (!String.IsNullOrWhiteSpace(personalcontact.Address))
                {
                    address.Desc = personalcontact.Address;
                    address.Default = true;
                    personalcontact.Address = String.Empty;
                }

                if (!String.IsNullOrWhiteSpace(personalcontact.PhoneNumber))
                {
                    phoneNumber.PhoneNo = personalcontact.PhoneNumber;
                    phoneNumber.Default = true;
                    personalcontact.PhoneNumber = null;
                }

                if (!String.IsNullOrWhiteSpace(personalcontact.IBAN))
                {
                    bank.IBAN = personalcontact.IBAN;
                    bank.Default = true;
                    personalcontact.IBAN = String.Empty;
                }

                #region Upload file
                if (upload != null && upload.ContentLength > 0)
                {
                    personalcontact.ImgFileName = System.IO.Path.GetFileName(upload.FileName);
                    personalcontact.ImgContentType = upload.ContentType;

                    #region Upload to Server
                    //****************************.
                    //Upload to Server
                    try
                    {
                        //Generate File Name for Upload on the Server 
                        string fileNameGen = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(upload.FileName);

                        personalcontact.ImgFileNameGen = fileNameGen;

                        //String path = Server.MapPath("~/files/") + fileNameGen; //"~/images/");
                        String path = Server.MapPath("~/files/") + fileNameGen; //"~/images/");
                        //upload.SaveAs(path + upload.FileName);
                        upload.SaveAs(path);
                    }
                    catch (Exception ex)
                    {
                        ViewBag.ErrorMessage = ex.Message;
                    }
                    //END Upload to Server
                    #endregion

                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        personalcontact.ImgContent = reader.ReadBytes(upload.ContentLength);
                    }
                }
                #endregion

                db.PersonalContacts.Add(personalcontact);
                db.SaveChanges();

                //New
                if (!String.IsNullOrWhiteSpace(address.Desc))
                {
                    address.PersonalContactID = personalcontact.PersonalContactID;
                    db.Addresses.Add(address);
                    db.SaveChanges();
                }

                if (!String.IsNullOrWhiteSpace(phoneNumber.PhoneNo))
                {
                    phoneNumber.PersonalContactID = personalcontact.PersonalContactID;
                    db.PhoneNumbers.Add(phoneNumber);
                    db.SaveChanges();
                }

                if (!String.IsNullOrWhiteSpace(bank.IBAN))
                {
                    bank.PersonalContactID = personalcontact.PersonalContactID;
                    db.Banks.Add(bank);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            return View(personalcontact);
        }

        // GET: /PersonalContacts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonalContact personalcontact = db.PersonalContacts.Find(id);
            if (personalcontact == null)
            {
                return HttpNotFound();
            }
            return View(personalcontact);
        }

        // POST: /PersonalContacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonalContactID,FirstName,SurName,DateOfBirth,Address,PhoneNumber,IBAN,ImgFileName,ImgContentType,ImgContent,ImgFileNameGen")] PersonalContact personalcontact, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                //Image 
                #region Upload the file (Delete previous)
                //****************************.
                //*** Upload the image file
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        //*isImageCh = true;

                        personalcontact.ImgFileName = System.IO.Path.GetFileName(upload.FileName);
                        personalcontact.ImgContentType = upload.ContentType;

                        #region Upload to Server
                        //********************
                        //Upload to Server
                        try
                        {
                            //Generate File Name for Upload on the Server 
                            string fileNameGen = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(upload.FileName);

                            personalcontact.ImgFileNameGen = fileNameGen;

                            String path = Server.MapPath("~/files/") + fileNameGen; //"~/images/");
                            //upload.SaveAs(path + upload.FileName);
                            upload.SaveAs(path);
                        }
                        catch (Exception ex)
                        {
                            ViewBag.Message = ex.Message;
                        }
                        //END Upload to Server
                        //********************
                        #endregion

                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            personalcontact.ImgContent = reader.ReadBytes(upload.ContentLength);
                        }

                        #region Delete previous file from Server
                        //******************************
                        //Delete previous file from Server 
                        try
                        {
                            PersonalContactDBContext dbREC = new PersonalContactDBContext();
                            PersonalContact personalcontactREC = dbREC.PersonalContacts.Find(personalcontact.PersonalContactID);
                            if(personalcontactREC.ImgFileNameGen != null)
                            {
                               System.IO.File.Delete(Server.MapPath("~/files/") + personalcontactREC.ImgFileNameGen);
                               ViewBag.Message = String.Format("{0} {1}", "Record Deleted File" ,personalcontactREC.ImgFileName);
                            }

                        }
                        catch (Exception ex)
                        {
                            ViewBag.ErrorMessage = ex.Message;
                        }
                        //******************************
                        #endregion

                    }


                }

                //*** END of Upload the image file
                //****************************.
                #endregion

                db.Entry(personalcontact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(personalcontact);
        }

        // GET: /PersonalContacts/Delete/5
        public ActionResult Delete(int? id)
        {

ManagingPersonalContacts/Views/Shared/_Layout.cshtml
@using ManagingPersonalContacts.Models;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Cookie ManagingPersonalContactsTheme -->
    @{
        if (Request.Cookies[Cookies.ManagingPersonalContactsTheme] != null)
        {
            if (Request.Cookies[Cookies.ManagingPersonalContactsTheme].Value.ToString() == true.ToString())
            {
                <link href="@Url.Content("~/Content/siteDark.css")" rel="stylesheet" />
            }
            else
            {
                <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" />
            }
        }
        else
        {
            <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" />
        }
    }
    <!-- END Cookie ManagingPersonalContactsTheme -->


    <!-- Toggle button Theme -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

            .switch input {
                opacity: 0;
                width: 0;
                height: 0;
            }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

            .slider:before {
                position: absolute;
                content: "";
                height: 26px;
                width: 26px;
                left: 4px;
                bottom: 4px;
                background-color: white;
                -webkit-transition: .4s;
                transition: .4s;
            }

        input:checked + .slider {
            background-color: #2196F3;
        }

        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        /* Rounded sliders */
        .slider.round {
            border-radius: 34px;
        }

            .slider.round:before {
                border-radius: 50%;
            }
    </style>
    <!-- END Toggle button Theme -->

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Manage Personal Contacts", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Personal Contacts", "Index", "PersonalContacts")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Managing Personal Contacts</p>

            <!-- Theme -->
            @Html.Partial("_PartialTheme")

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ManagingPersonalContacts/Views/Shared/_PartialTheme.cshtml
@using ManagingPersonalContacts.Models;

<!-- Toggle Button Theme -->
<script>
    function CallChangeTheme(value) {
        //LoadWait();

        var checkBox = document.getElementById("myCheck");
        var text = document.getElementById("text");
        text.style.display = "block";

        //window.location.href = "/UserRegBlocks/ChangeTheme?value=" + value;
        window.location.href = "/Cookies/ChangeTheme?value=" + checkBox.checked;

        //*alert('Changing theme');
    }
</script>

@{if (Request.Cookies[Cookies.ManagingPersonalContactsTheme] != null)
{
    if (Request.Cookies[Cookies.ManagingPersonalContactsTheme].Value.ToString() == true.ToString())
    {
        <label class="switch">
            <input type="checkbox" checked id="myCheck" onchange="CallChangeTheme(this.value)">
            <span class="slider round"></span>
        </label>
        <b>Dark Theme</b>
    }
    else
    {
        <label class="switch">
            <input type="checkbox" id="myCheck" onchange="CallChangeTheme(this.value)">
            <span class="slider round"></span>
        </label>
        <b>Ligh Theme</b>
    }
}
else
{
    <label class="switch">
        <input type="checkbox" id="myCheck" onchange="CallChangeTheme(this.value)">
        <span class="slider round"></span>
    </label>
    <b>Ligh Theme</b>
}
}

<p id="text" style="display:none">
    <b>
        Loading ...
    </b>
</p>

@*
    <label class="switch">
        <input type="checkbox" id="myCheck" onchange="CallChangeTheme(this.value)">
        <span class="slider round"></span>
        <b>Dark theme</b>
    </label>

    <p id="text" style="display:none">Theme changed</p>
*@

@*
    <label class="switch">
        <input type="checkbox" checked onchange="CallChangeTheme(this.value)">
        <span class="slider round"></span>
    </label>
*@
<!-- END Toggle Button Theme -->
